insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('braden88', 'F9DNb1surVlB', 'Braden', 'Ang', 89485238, 'Kent Ridge', '$18.19');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('coop75', 'yzKcsIDT5d2', 'Coop', 'Zhuo', 92651982, 'Eusoff', '$63.45');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('donn99', 'IpBRjyv2AW2', 'Donn', 'Lam', 93828334, 'Raffles', '$37.86');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hershel63', 'ESChlvijKJG', 'Hershel', 'Yuen', 94903278, 'Eusoff', '$12.49');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bendite100', 'SVwTovELnvf8', 'Bendite', 'Ko', 81357991, 'Temasek', '$39.66');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('arlin4', 'FkkFXtyZ', 'Arlin', 'Chan', 87511368, 'Raffles', '$34.36');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('clarey2', 'KdfRn7Q48', 'Clarey', 'Ko', 85440341, 'Temasek', '$8.05');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cirillo31', 'oSYUWDraCx', 'Cirillo', 'Goh', 89231863, 'Sheares', '$32.03');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('blondelle37', 'FXoLMT', 'Blondelle', 'Chong', 93015591, 'Kent Ridge', '$10.23');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('eugen89', 'f1WEwXKmq', 'Eugen', 'Shih', 82246582, 'Temasek', '$19.18');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nataline55', 'zclOlj', 'Nataline', 'Lee', 87633576, 'Raffles', '$20.12');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('beau78', 'I5utbBH2mk', 'Beau', 'Lee', 88151364, 'Eusoff', '$21.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nappy15', 'vFNMRcY5rLhZ', 'Nappy', 'Chan', 86143817, 'Temasek', '$27.05');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('helli68', 'IO6sXkvRKWUs', 'Helli', 'Li', 93522787, 'Kent Ridge', '$60.76');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('katha82', 'wZoq9pNzy', 'Katha', 'Low', 81931955, 'Temasek', '$24.31');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('charissa62', 'kCCaeP3YzPwH', 'Charissa', 'Goh', 97954495, 'Eusoff', '$55.18');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cliff77', 'G3OAziVvYQp', 'Cliff', 'Leng', 93459080, 'Temasek', '$61.96');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('horatius54', 'tkI7kC', 'Horatius', 'Kang', 88096088, 'Sheares', '$12.77');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('shannon63', 'RJUP7KV', 'Shannon', 'Leng', 90530355, 'Temasek', '$31.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('germaine11', 'tDCwGbC', 'Germaine', 'Ko', 97942035, 'Sheares', '$27.30');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ariel30', '5SKx2xv', 'Ariel', 'Leng', 88794380, 'Eusoff', '$13.52');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('aila37', 'vMoHSSjlx', 'Aila', 'Shih', 89299804, 'Kent Ridge', '$32.83');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hartwell26', '2Mnnsz', 'Hartwell', 'Kong', 87927152, 'Sheares', '$43.14');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('parke14', 'cWSnjSA', 'Parke', 'Cho', 93497206, 'Kent Ridge', '$44.19');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kory6', 'kXPbfK02tw6', 'Kory', 'Chong', 88881986, 'Sheares', '$26.68');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sumner40', '1W8ASw', 'Sumner', 'Lam', 81663711, 'King Edward VII', '$7.42');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jessa59', 'YhJAJr2k4', 'Jessa', 'Xu', 84052889, 'Eusoff', '$24.46');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('eduardo71', 'VD9hJbp', 'Eduardo', 'Ko', 90850867, 'Eusoff', '$19.63');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('glynda26', 'BIyaSWx', 'Glynda', 'Cheang', 95441412, 'Kent Ridge', '$63.32');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cathrin35', 'dlvpQx', 'Cathrin', 'Toh', 92910648, 'Raffles', '$57.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cherri85', '0xF71ZgdU', 'Cherri', 'Ow', 95495974, 'King Edward VII', '$39.62');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tull25', 'KAlY4lA', 'Tull', 'Chng', 98133253, 'Eusoff', '$52.75');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('onida36', '7Cgk4m', 'Onida', 'Qiu', 98132275, 'Raffles', '$40.98');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ferdinanda8', '3Hu69sUZ3', 'Ferdinanda', 'Pang', 92066632, 'Eusoff', '$57.77');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('anatola80', '7KocH3X', 'Anatola', 'Tan', 84248138, 'King Edward VII', '$7.65');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dalia34', 'gHELtjZYFii2', 'Dalia', 'Lee', 88182048, 'Temasek', '$25.72');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sharla41', '7apjxKH', 'Sharla', 'Wen', 86698228, 'Raffles', '$19.77');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('carley92', 'VYn9LODmTpM', 'Carley', 'Chng', 98914341, 'Eusoff', '$16.00');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gloriane13', 'JU7K4u3', 'Gloriane', 'Peng', 87679501, 'Temasek', '$37.16');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ernst55', 'zaqtsSijdI', 'Ernst', 'Ow', 95432894, 'Temasek', '$54.87');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sibylle38', 'hoNp66lPrem', 'Sibylle', 'Kwa', 91623221, 'King Edward VII', '$45.74');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('teodora28', 'ivKisvj', 'Teodora', 'Khan', 91601593, 'Sheares', '$24.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('willard64', 'MqLO06Kfv', 'Willard', 'Tang', 93273006, 'King Edward VII', '$10.57');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rachelle8', 'YdEv6W2Zc', 'Rachelle', 'Nagaratnam', 97998275, 'Temasek', '$44.15');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('calley39', 'tm8CEKceVz', 'Calley', '', 86063235, 'Sheares', '$24.94');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hugibert55', 'vdcHhUwgt5m', 'Hugibert', 'Cho', 86935513, 'Raffles', '$60.09');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('baron33', 'Zfgmlmoiu', 'Baron', 'Tan', 90480799, 'King Edward VII', '$13.67');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('guendolen97', 'UwjpHo', 'Guendolen', 'Peng', 81320704, 'Kent Ridge', '$54.36');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('daveta38', 'Vf3sVIN', 'Daveta', 'Chong', 90622506, 'King Edward VII', '$7.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('garreth60', 'piL23bcwaBg', 'Garreth', '', 98269999, 'Temasek', '$11.53');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('waneta17', 'z3DJj1', 'Waneta', 'Nagaratnam', 94581604, 'Temasek', '$49.07');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('doe26', 'OMKzAkELbD', 'Doe', 'Qiu', 82786981, 'Sheares', '$12.27');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jim34', 'IUKLyVcMRyuJ', 'Jim', 'Goh', 82992162, 'King Edward VII', '$33.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nonah56', 'CLo7PfpZxgQ8', 'Nonah', 'Low', 88418004, 'Kent Ridge', '$27.01');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('berna37', '4Eg3PTc68pDm', 'Berna', 'Teh', 82357345, 'Eusoff', '$7.06');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('carmina45', '8Xg6fmC', 'Carmina', 'Rao', 95943224, 'Kent Ridge', '$38.20');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('emmalynn77', 'Lfwlj58', 'Emmalynn', 'Leng', 95709831, 'Temasek', '$23.79');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gena8', 'flqQG3GxER', 'Gena', 'Seah', 90393229, 'King Edward VII', '$7.69');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('christalle9', 'r3pJjKy', 'Christalle', 'Pang', 87513010, 'Temasek', '$61.53');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lonna27', 'wl2kkxVJJI', 'Lonna', 'Lee', 90368311, 'King Edward VII', '$11.96');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('fulton4', 'gTn3NSi6J', 'Fulton', 'Puah', 85834091, 'Kent Ridge', '$40.08');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('malissia60', 'BCKhmCAlJo7m', 'Malissia', 'Huang', 93705817, 'Eusoff', '$5.18');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gerrie16', 'VeUHeV', 'Gerrie', 'Low', 86518968, 'Temasek', '$49.87');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('liane81', 'XJ83qP', 'Liane', 'Khatri', 86271765, 'Eusoff', '$30.65');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('quincey61', '9zzdaX', 'Quincey', 'Chan', 90653913, 'King Edward VII', '$49.61');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('weber90', 'gBjulypWku', 'Weber', 'Tan', 90870300, 'Kent Ridge', '$22.44');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('beth26', 'ri8sfAGXcaD', 'Beth', 'Khatri', 87885969, 'Raffles', '$44.51');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('durante71', 'o4CL51Y1DW', 'Durante', 'Cho', 94665682, 'Temasek', '$33.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('suzanne2', 'UcBGiRFdiQ', 'Suzanne', 'Lim', 84801790, 'Sheares', '$5.38');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('aleksandr75', 'z4IR1w90', 'Aleksandr', 'Tan', 82912307, 'Kent Ridge', '$33.52');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('milton38', 'X69HdxNDlpD', 'Milton', 'Low', 84594281, 'Eusoff', '$31.38');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('catha79', 'EGM5kqJE4B4', 'Catha', 'Lau', 95188906, 'Temasek', '$5.74');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('merrili33', 'apNCAHLOHF', 'Merrili', 'Tang', 86549782, 'Eusoff', '$55.03');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('chaunce71', 'F314sM3X', 'Chaunce', 'Zhuo', 91891824, 'Raffles', '$33.04');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nolan41', 'LGB8AYxu3', 'Nolan', 'Lam', 93795306, 'Sheares', '$31.45');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bobby48', 'EfBCxkfB', 'Bobby', 'Anandarajah', 92638787, 'Sheares', '$6.18');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('deborah16', 'EG2tHlJZ9', 'Deborah', 'Anandarajah', 91404460, 'Kent Ridge', '$35.61');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('harrison39', 'CciYzDsZGei', 'Harrison', 'Peng', 86761597, 'Sheares', '$64.66');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('zachariah13', 'jdGqoQaKWeT', 'Zachariah', 'Low', 84174003, 'Kent Ridge', '$24.06');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('denys98', 'LFkN7Rss', 'Denys', 'Khatri', 91190443, 'Raffles', '$42.14');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('truda5', 'cJRT1kV95j', 'Truda', 'Jiang', 85968135, 'Sheares', '$58.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sven42', 'B3y5Lh1gV', 'Sven', 'Fan', 91961304, 'King Edward VII', '$43.32');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kahlil56', 'ZAYyBYQZjL', 'Kahlil', 'Sim', 85673885, 'King Edward VII', '$47.05');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('karol92', 'HqPeJ1X4dBp', 'Karol', 'Shih', 88097316, 'Raffles', '$21.34');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cart57', 'Tgof6JV59', 'Cart', 'Yuen', 85252857, 'Raffles', '$20.13');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('madelena45', 'AsQPGd8', 'Madelena', 'Qiu', 83099288, 'Raffles', '$19.10');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('marshall34', 'QgUg8qlCtfP8', 'Marshall', 'Toh', 87446917, 'Eusoff', '$38.08');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('vinny18', '502ZcX2kAQKN', 'Vinny', 'Khatri', 88869345, 'Raffles', '$64.15');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('danica38', '5AJdSjQ', 'Danica', 'Xue', 91257657, 'Temasek', '$53.56');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('carlie89', 'SmCWgz8n', 'Carlie', 'Rao', 98163810, 'Eusoff', '$53.94');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lindi44', '5vkKgypBd5qd', 'Lindi', 'Huang', 90849204, 'Kent Ridge', '$57.76');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('roderick4', 'YVLKCnKb', 'Roderick', 'Li', 86969286, 'Raffles', '$9.27');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('paddy92', 'JNm1Q8QBGOK', 'Paddy', 'Tang', 85017167, 'Raffles', '$9.20');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jeniffer6', 'sAbY5uEjmhRF', 'Jeniffer', 'Fan', 95753634, 'Raffles', '$51.00');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('fabio40', '5mUoj2u', 'Fabio', 'Low', 87749250, 'Eusoff', '$35.84');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sonnnie65', 'GJcb7p0F', 'Sonnnie', 'Kuok', 88873945, 'King Edward VII', '$40.01');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('halie47', 'MSnpPENg2G', 'Halie', 'Yuen', 89934502, 'Sheares', '$21.70');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('zola73', '9yOBjZwtmLZ9', 'Zola', 'Zhang', 95064979, 'Kent Ridge', '$30.05');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('aridatha52', 'CJDh22a9Qk', 'Aridatha', 'Anandarajah', 90459482, 'Sheares', '$45.56');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dorothee69', 'lgLRjl9lBu', 'Dorothee', 'Yuen', 89093601, 'Temasek', '$53.93');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jeddy75', 'exgekgW4X5Y', 'Jeddy', 'Khan', 96034179, 'King Edward VII', '$38.09');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jennee57', 'gj42NDNDD', 'Jennee', 'Rao', 82245870, 'King Edward VII', '$19.39');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('derek69', 'R8z9tISC', 'Derek', 'Seah', 96483588, 'Raffles', '$37.32');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dael19', 'xc5ZTLzTN', 'Dael', 'Kuok', 89342118, 'Eusoff', '$36.58');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cody17', 'LklIsdqOhxX', 'Cody', 'Ko', 94889360, 'Eusoff', '$42.30');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dionisio59', 'Hz5nk56QZYRY', 'Dionisio', 'Yuen', 84658123, 'Raffles', '$15.03');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('pip70', '8yYXZTwgQQ', 'Pip', 'Zhang', 95820780, 'King Edward VII', '$55.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('berny41', 'dYjcMDb', 'Berny', 'Chen', 96167849, 'Kent Ridge', '$43.77');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cthrine54', 't8XidLD3uey', 'Cthrine', 'Xue', 94786164, 'Temasek', '$34.67');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bogey17', 'OBQI3EZ', 'Bogey', 'Nagaratnam', 93160545, 'Temasek', '$42.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('belia81', 'wpohVYk', 'Belia', 'Li', 95704081, 'Raffles', '$12.13');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tanitansy60', 'paDSYQO84', 'Tanitansy', 'Ko', 85483215, 'Kent Ridge', '$64.96');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('vaclav100', 'WCQNZsq', 'Vaclav', 'Mun', 82953798, 'Sheares', '$13.63');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('arluene65', 'PlPh4yeBhDB6', 'Arluene', 'Khatri', 85862021, 'Raffles', '$14.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('joby25', 'GhkADH2v4pJU', 'Joby', 'Wen', 98833681, 'Eusoff', '$39.06');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sheridan40', 'Rz0W0JWtffqq', 'Sheridan', 'Ang', 83911101, 'Temasek', '$14.23');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('shandy59', 'M45aXB', 'Shandy', 'Li', 92706373, 'Temasek', '$35.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rowen14', 'leeimf4ErF', 'Rowen', 'Ma', 81585877, 'Eusoff', '$33.47');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tracee66', '1IYzxG4N', 'Tracee', 'Lim', 94801266, 'Temasek', '$50.44');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lind74', 'vwmOKsMXExdm', 'Lind', 'Kang', 89895480, 'Sheares', '$26.89');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('eberto69', '4vmJv3RBhpo6', 'Eberto', 'Low', 84526222, 'King Edward VII', '$46.27');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('salmon20', 'AVGHQnoNzC', 'Salmon', 'Chong', 91241758, 'Kent Ridge', '$17.50');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('elyse96', 'kDpXMf0', 'Elyse', 'Pang', 91797564, 'Kent Ridge', '$22.71');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('faythe11', 'fXQOHPCYMQ', 'Faythe', 'Lau', 95126750, 'Kent Ridge', '$34.09');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('trude10', 'TxIw0A', 'Trude', 'Xue', 94821892, 'Sheares', '$54.71');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kiel12', 'ACNQTA986r5', 'Kiel', 'Yuen', 84808172, 'Sheares', '$46.40');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('brittani28', 'zf2wgVRN0yRI', 'Brittani', 'Li', 87588022, 'Temasek', '$31.54');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hersh83', 'ClyiWJe', 'Hersh', 'Chong', 88754945, 'Eusoff', '$18.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rob38', 'Pdeoq3Nc', 'Rob', 'Nagaratnam', 83120537, 'Temasek', '$29.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('toiboid27', 'aW6SFVXli3zh', 'Toiboid', 'Lau', 87617164, 'Eusoff', '$32.69');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('joy84', 'UFUivn68', 'Joy', 'Jiang', 95276924, 'Temasek', '$51.84');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nicolina33', 'bU4Ogg', 'Nicolina', 'Chan', 94096589, 'Kent Ridge', '$13.15');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('josepha35', '75jhvO9Z0oF8', 'Josepha', 'Khatri', 88045452, 'Sheares', '$10.82');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ursola20', 'fQkDadm', 'Ursola', 'Kwa', 84549279, 'Kent Ridge', '$23.27');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tierney12', 'Q7ooPBBGyLW', 'Tierney', 'Chan', 82347373, 'King Edward VII', '$32.76');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('daven36', '4ADOI3zf7t', 'Daven', 'Khatri', 98113171, 'Kent Ridge', '$30.69');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('katerine24', 'WGUx6wYLM', 'Katerine', 'Chan', 86437957, 'Temasek', '$23.27');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sonny32', 'Rfaoro5', 'Sonny', '', 92405487, 'Raffles', '$24.30');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('fran65', 'Zjw9wC1vUt', 'Fran', 'Teh', 84641774, 'Sheares', '$25.60');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kevan23', 'pKoMYIuefs', 'Kevan', 'Xu', 98816773, 'Sheares', '$18.10');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('fanni82', 'EYywU1Y6', 'Fanni', 'Mun', 81763929, 'Temasek', '$62.01');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('heda52', 'tfqkKLLI2', 'Heda', 'Fan', 94549955, 'King Edward VII', '$54.66');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('oliy99', 'Le8DQe', 'Oliy', 'Khan', 92366265, 'Temasek', '$30.01');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cammy2', 'wpTW9gdfd9', 'Cammy', 'Chan', 95185978, 'Eusoff', '$55.45');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rogers24', 'v781hdXOMOKc', 'Rogers', 'Huang', 86884040, 'King Edward VII', '$39.51');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('yulma11', 'D5JbHGgTkh', 'Yulma', 'Seet', 92433961, 'Eusoff', '$54.84');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tildy18', 'B5jJ9sYmNN', 'Tildy', 'Fan', 92325861, 'Sheares', '$11.73');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lucho82', 'fHzVhiuraX', 'Lucho', 'Low', 81279794, 'Sheares', '$57.06');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('justis19', 'B1R7GgpZH5', 'Justis', 'Yuen', 82186990, 'Raffles', '$57.23');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('codee83', 'CMECJMil8o', 'Codee', 'Kuok', 97577507, 'Kent Ridge', '$14.57');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('arlen79', 'zfVwl1c', 'Arlen', 'Huang', 98632132, 'Eusoff', '$46.79');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sharline40', 'NPrCpoBKgm', 'Sharline', 'Rao', 81245653, 'King Edward VII', '$64.96');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('robers39', 'kFfWzdtvA0xV', 'Robers', 'Cheang', 98968882, 'King Edward VII', '$27.02');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('francesco67', '54kYmUVnmk', 'Francesco', 'Nagaratnam', 96833465, 'Kent Ridge', '$41.18');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('elayne85', 'zd9klJ', 'Elayne', 'Khatri', 82905489, 'Temasek', '$55.21');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('shellysheldon69', 'ZOQmFfnE', 'Shellysheldon', 'Li', 94230221, 'King Edward VII', '$27.07');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gilbert34', 'UNPOMcR', 'Gilbert', 'Chan', 94827781, 'Temasek', '$13.68');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('francis99', 'WJOyDIaoZ', 'Francis', 'Chen', 84282801, 'Eusoff', '$63.58');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('daryl19', 'VuBM3AYeCy', 'Daryl', 'Kuok', 82524357, 'Eusoff', '$57.19');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('glennis74', 'VtEDlxmahrK', 'Glennis', 'Nagaratnam', 89357716, 'King Edward VII', '$10.34');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lou11', 'rn0RgvGhCGH4', 'Lou', 'Toh', 83238632, 'Temasek', '$7.43');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('aldin76', 'C9miQKg7', 'Aldin', 'Toh', 92236987, 'Raffles', '$25.23');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('barbey50', 'asEmogB', 'Barbey', 'Chen', 83656053, 'Temasek', '$9.46');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rochell37', 'aXgZmJ9uJF', 'Rochell', 'Ang', 96555548, 'Kent Ridge', '$33.87');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('leontyne90', '7GhoAFr', 'Leontyne', 'Kuok', 90920439, 'Raffles', '$16.87');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tucky57', 'Yg60TAwVL', 'Tucky', 'Shih', 94870125, 'King Edward VII', '$28.47');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('anders10', 'bUUIvwF4', 'Anders', 'Mun', 81312262, 'Kent Ridge', '$56.27');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kacey98', 'dITXfV', 'Kacey', 'Anandarajah', 87172593, 'Eusoff', '$29.76');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('vivianne20', 'TGwOtMr9x', 'Vivianne', 'Tan', 90476971, 'Sheares', '$53.37');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('carey20', 'r4O1fEj', 'Carey', 'Pang', 98652503, 'Raffles', '$22.86');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('frazer39', 'AbhrBtprW', 'Frazer', 'Pang', 92731665, 'Sheares', '$6.52');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sallee55', 'PDxWJn48i', 'Sallee', 'Shih', 82433973, 'Kent Ridge', '$9.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gabbi97', '2zv4U7kqb', 'Gabbi', 'Peng', 88830133, 'Kent Ridge', '$49.61');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lilian9', 'z8cpjrJ2', 'Lilian', 'Seet', 91330230, 'Sheares', '$15.20');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('amelita14', 'CaU6B2s', 'Amelita', 'Zhuo', 90999854, 'Eusoff', '$35.04');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('minor43', 'SvUJzqa6', 'Minor', 'Wen', 86817075, 'Eusoff', '$39.40');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lev15', '1a4dczC0Ov', 'Lev', 'Kong', 95442930, 'Raffles', '$35.43');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('marci3', 'SXGdzi3lt', 'Marci', 'Seet', 88004576, 'Kent Ridge', '$28.89');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nicholle42', '6EIQMU', 'Nicholle', 'Wen', 83232351, 'Temasek', '$22.50');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('vanya28', '6CeFXji3n', 'Vanya', 'Kong', 89727281, 'King Edward VII', '$58.88');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cazzie42', 'ZSIkZ19i', 'Cazzie', 'Yuen', 89972470, 'Raffles', '$10.72');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('iorgos90', 'EBWwACH', 'Iorgos', 'Low', 91158434, 'King Edward VII', '$31.74');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dannel27', 'rx9iNNR', 'Dannel', 'Shih', 83767563, 'King Edward VII', '$30.36');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rosella77', 'pF76Qgnup2J', 'Rosella', 'Seet', 97499438, 'Kent Ridge', '$5.32');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('morganica89', 'Zj3PaWKXyZ', 'Morganica', 'Fan', 87386261, 'Temasek', '$16.19');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('andy95', 'QbLobWCaGd', 'Andy', 'Tang', 83594782, 'Kent Ridge', '$22.41');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('carmela22', 'fes1StSimt', 'Carmela', 'Tang', 84271023, 'Kent Ridge', '$58.90');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lombard72', 'Ae27sUcEO', 'Lombard', 'Lee', 90067471, 'Raffles', '$41.01');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('berti44', 'z2KUnH3Yg9L', 'Berti', 'Ang', 84645854, 'Eusoff', '$58.53');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dido80', 'tpWeMek9dW', 'Dido', 'Zhuo', 81945674, 'Eusoff', '$42.45');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('oswald70', 'zeAOx6p', 'Oswald', 'Jiang', 88146815, 'Kent Ridge', '$32.45');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('robinson90', 'H40fpwZOj1lf', 'Robinson', 'Rao', 93786281, 'Eusoff', '$6.25');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('benson6', 'i2s56LktnBi6', 'Benson', 'Khatri', 96832779, 'King Edward VII', '$56.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ringo61', 'ePHj7Wd1', 'Ringo', 'Rao', 87823064, 'King Edward VII', '$39.34');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('peggi35', 'NoSEXpsgHc4', 'Peggi', '', 95923805, 'Eusoff', '$54.13');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jess6', 'uTWfklIoe4j', 'Jess', 'Wong', 90830420, 'Raffles', '$23.29');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bill40', 'ucmeePYbC', 'Bill', 'Lam', 91182859, 'Eusoff', '$54.82');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('berte75', '91zEItbbk7D', 'Berte', 'Anandarajah', 87043142, 'King Edward VII', '$23.42');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jammal94', 'nKhZAw', 'Jammal', 'Ow', 81174250, 'King Edward VII', '$24.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('zedekiah95', 'fYPwx0mMLZho', 'Zedekiah', 'Chan', 91884406, 'King Edward VII', '$25.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('millicent69', 'QQ9lR14vXkNx', 'Millicent', 'Lee', 90446579, 'Sheares', '$27.99');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('joelly78', 'Zph5Mzfo2XA', 'Joelly', 'Xue', 92733526, 'King Edward VII', '$32.71');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('mona99', 'c8kg9e', 'Mona', 'Khatri', 91467360, 'King Edward VII', '$33.36');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cheri84', 'OuPnfEDEaRb', 'Cheri', 'Cho', 92396787, 'Sheares', '$5.65');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('johnny39', '8s611fODwQb', 'Johnny', 'Wen', 89302250, 'King Edward VII', '$60.38');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('matthieu91', 'UZTTIGykCg3', 'Matthieu', 'Mun', 82242578, 'Temasek', '$57.85');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('scarlet53', 'FhXhONh', 'Scarlet', 'Puah', 94993470, 'King Edward VII', '$48.49');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('leyla93', 'kt5vhFYh8gM', 'Leyla', 'Zhang', 84397057, 'Kent Ridge', '$54.58');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cordey89', 'ptt0ZGervHD', 'Cordey', 'Ko', 91501151, 'Temasek', '$29.61');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('coop89', 'qQsy8kwJP', 'Coop', 'Peng', 85855336, 'Temasek', '$64.25');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('alexandrina65', 'o4sERnqk', 'Alexandrina', 'Chan', 81419796, 'Kent Ridge', '$54.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('arielle37', 'wFsUHxNyf', 'Arielle', 'Khatri', 94676099, 'Sheares', '$40.39');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('giustino6', 'wByhw2sH6tb', 'Giustino', 'Chng', 89731262, 'Temasek', '$39.17');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bernita78', 'XiYWcJ1p', 'Bernita', 'Chan', 83521190, 'Raffles', '$30.59');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('adrian44', 'ZqHG8G', 'Adrian', 'Ang', 89271092, 'Temasek', '$58.95');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('raquela61', 'jYtnVcj', 'Raquela', 'Huang', 89855223, 'Eusoff', '$10.90');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('valina63', 'JFX53R', 'Valina', 'Lau', 91347116, 'Eusoff', '$55.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('minor32', 'B7nRY0NOrDEc', 'Minor', 'Anandarajah', 91531928, 'Eusoff', '$19.04');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ruthe5', 'fdJ9BCvLTH', 'Ruthe', 'Xu', 92109249, 'Raffles', '$12.37');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sara37', 'pfk8I6H7jOw', 'Sara', 'Rao', 92311446, 'Temasek', '$60.20');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('basia22', 'JNHdX6FMHt', 'Basia', 'Nagaratnam', 91290292, 'Temasek', '$64.26');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dewey33', 'AvEOtHlT3dB', 'Dewey', 'Patel', 90373569, 'Raffles', '$47.03');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('debby1', 'Eys3rnA', 'Debby', 'Xue', 81377487, 'Raffles', '$14.39');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('estrellita29', '1dz87Y', 'Estrellita', 'Lam', 93570598, 'Temasek', '$8.23');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('florance62', 'b1dWMt4TW', 'Florance', 'Cho', 93439880, 'Eusoff', '$51.16');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bartie50', 'a09x5u0d4ylw', 'Bartie', 'Ang', 86710603, 'Sheares', '$5.76');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('donnell78', 'vPKq6V', 'Donnell', 'Peng', 82075460, 'Sheares', '$12.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ag45', 'pYHblegU', 'Ag', 'Pang', 88204638, 'King Edward VII', '$10.70');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sancho81', 'bjGd9qg', 'Sancho', 'Xue', 92546900, 'Temasek', '$23.60');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('virgie20', 'uO42fpKI', 'Virgie', 'Low', 83980739, 'Kent Ridge', '$11.55');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('haskel54', 'R510mbTuD7i6', 'Haskel', 'Ma', 84498030, 'Eusoff', '$8.55');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jobey41', 'd1zIw3', 'Jobey', 'Zhang', 90121602, 'Eusoff', '$11.10');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('luke37', 'awZtm9d', 'Luke', 'Yang', 91806106, 'Temasek', '$41.01');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gracie23', '5pQaBDtY2p2', 'Gracie', 'Kang', 96886421, 'King Edward VII', '$31.45');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('goldi55', 'Y9XBC1VT', 'Goldi', 'Puah', 92566133, 'Sheares', '$27.06');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('emmey93', 'jNK0oixphNGF', 'Emmey', 'Chan', 81174631, 'Eusoff', '$11.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('emanuel19', 'WtI39o13Blv', 'Emanuel', 'Pang', 85388527, 'Kent Ridge', '$21.88');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rhodie83', 'ibZJ7B18Uk', 'Rhodie', 'Nagaratnam', 88767994, 'Sheares', '$31.51');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('doria6', 'Subvtv3Ytg', 'Doria', 'Khatri', 82842828, 'King Edward VII', '$51.20');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('roi24', 'yPC7HZ', 'Roi', 'Sim', 81627328, 'Raffles', '$37.32');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('conant10', 'uLrlF1U', 'Conant', 'Mun', 86583306, 'Temasek', '$38.57');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('reeta63', 'PzjmrCekl', 'Reeta', 'Anandarajah', 89393339, 'Kent Ridge', '$27.99');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('janey89', 'ZM0Oa7JN7qPP', 'Janey', 'Chan', 87856784, 'Raffles', '$60.82');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('joyous80', '9w8px2OrQgJ', 'Joyous', 'Qiu', 94080781, 'King Edward VII', '$29.34');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dierdre75', '1R6rsdSHVt', 'Dierdre', 'Lim', 92908344, 'Raffles', '$33.14');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('faye52', 'vFdnnWDqdm6', 'Faye', 'Huang', 90186623, 'Sheares', '$52.78');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('moselle57', 'Hjw9Hk', 'Moselle', 'Lim', 81495505, 'Kent Ridge', '$58.14');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('olenka7', '4L5cVMVgQ', 'Olenka', 'Goh', 88692139, 'Sheares', '$18.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('edward53', '6g10LTTPA', 'Edward', 'Goh', 85636356, 'Sheares', '$60.70');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('walther45', '6uLUKZLvUE', 'Walther', 'Peng', 84653336, 'Temasek', '$50.39');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('elmore42', 'bvPif5', 'Elmore', 'Toh', 97393795, 'Temasek', '$19.54');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jonas43', 'JVO13dA', 'Jonas', 'Chen', 93488641, 'Sheares', '$15.31');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('leone7', 'PgTEbAh2ZHez', 'Leone', 'Huang', 95145150, 'Temasek', '$63.53');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('muffin94', 'D5HG2MJ', 'Muffin', 'Chng', 88697265, 'King Edward VII', '$39.83');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dacia28', 'jXqUWjPI2', 'Dacia', 'Tang', 90322996, 'Temasek', '$53.71');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('norene63', 'A1dyEhNN8', 'Norene', 'Chng', 84500849, 'Sheares', '$11.86');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('arv5', 'QITRZTJ', 'Arv', 'Rao', 95458829, 'Eusoff', '$26.59');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rahel100', '7RKWxJm9', 'Rahel', 'Ow', 95258491, 'Kent Ridge', '$64.18');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('franklin59', 'HLe59WIBcK', 'Franklin', 'Seah', 90164325, 'Sheares', '$59.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jane60', 'IHpThp6', 'Jane', 'Kuok', 86751446, 'Temasek', '$21.74');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sue87', 'IHMlkbQdV', 'Sue', 'Li', 96375654, 'Kent Ridge', '$19.34');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rorke75', 'fEK2Ty', 'Rorke', 'Puah', 94577784, 'Eusoff', '$18.24');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('quinn40', 'qrFxeGVFY', 'Quinn', 'Rao', 84155556, 'Temasek', '$37.66');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('free94', 'gDNm1twWLqkD', 'Free', 'Chong', 83806514, 'Temasek', '$45.42');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nick25', '20ZO3dQdl5JA', 'Nick', 'Ma', 89174505, 'King Edward VII', '$13.06');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('therese62', 'hbUKvXoXxj', 'Therese', 'Yang', 96133508, 'Kent Ridge', '$39.37');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('pyotr57', '3Xar5IU', 'Pyotr', 'Pang', 96732338, 'Raffles', '$46.52');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('trevar60', 'LEK9eopGO', 'Trevar', 'Teh', 98038723, 'Raffles', '$18.25');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('fritz43', 'VA3XAjCwLX91', 'Fritz', 'Leng', 81001856, 'Raffles', '$45.40');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('daffi30', 'fiMx3byW', 'Daffi', 'Chong', 90923367, 'Temasek', '$23.61');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('wynne15', 'U0dE5FonOp', 'Wynne', 'Seet', 98213361, 'Eusoff', '$49.74');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kaylee2', '83GZDa4', 'Kaylee', 'Kong', 87366188, 'Raffles', '$27.15');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('yoshi97', 'G2LQtek', 'Yoshi', 'Tang', 90881861, 'Kent Ridge', '$35.81');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('odelia14', 'zkfc4GPUWEc', 'Odelia', 'Toh', 82150988, 'Eusoff', '$5.88');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('andree9', '3iZp2G', 'Andree', 'Kwa', 84104687, 'Kent Ridge', '$40.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('whit87', 'LFZHxwzDyD6', 'Whit', 'Xue', 82204769, 'Eusoff', '$58.32');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gibb8', 'Q3INxP', 'Gibb', 'Seah', 83592861, 'Eusoff', '$10.59');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('maison58', 'UeQ1UPxcqJw', 'Maison', 'Teh', 88390960, 'King Edward VII', '$51.15');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('erminia81', 'dShuSBRfuy0', 'Erminia', 'Kong', 84367325, 'Temasek', '$40.62');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bronnie11', '0gYLLR', 'Bronnie', 'Kong', 94016606, 'Temasek', '$49.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lucina50', 'R0QPNpB', 'Lucina', 'Lau', 82589216, 'Temasek', '$43.06');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sydney25', 'aejFSST', 'Sydney', 'Xu', 93865777, 'King Edward VII', '$52.02');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sophi26', 'NznlitC', 'Sophi', 'Khatri', 97860590, 'King Edward VII', '$45.05');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('garwin100', 'KDcWKB', 'Garwin', 'Kuok', 87324730, 'Eusoff', '$35.93');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('eddy12', '9QWFBf1X483m', 'Eddy', 'Ma', 97636715, 'Raffles', '$12.27');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('herc10', 'PWhm8bOLaNP', 'Herc', 'Seet', 93040043, 'Temasek', '$58.94');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('job66', 'ids00M', 'Job', 'Mun', 89405015, 'Kent Ridge', '$38.59');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('mary26', '2gWnQi', 'Mary', 'Rao', 82314284, 'King Edward VII', '$14.43');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('webb2', 'ryP4Z7jHII', 'Webb', 'Wong', 90057762, 'Kent Ridge', '$29.13');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('iolande3', 'qmVEXubAHg', 'Iolande', 'Jiang', 84549130, 'Raffles', '$31.85');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kellina54', 'b5juPg', 'Kellina', 'Zhuo', 98862174, 'Raffles', '$15.21');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('eugenio11', 'yrGZcumoJG', 'Eugenio', 'Ma', 94783691, 'Sheares', '$32.77');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nana82', 'WC6MZOYPhSI', 'Nana', 'Seet', 90818495, 'Sheares', '$62.19');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('willard56', 'cYNXWs62X3Y', 'Willard', 'Chen', 90914620, 'Raffles', '$21.93');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cleopatra53', 'zGzjuitZuzox', 'Cleopatra', 'Lam', 92187823, 'Eusoff', '$55.52');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('easter9', 'jsf9r7a', 'Easter', 'Yuen', 93753391, 'King Edward VII', '$12.93');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tobe11', 'GZ794IG3', 'Tobe', 'Yuen', 87694324, 'Temasek', '$35.52');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('isak65', 'JuQEHzC', 'Isak', 'Anandarajah', 85587509, 'Temasek', '$32.50');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('mart78', 'uMk2Wcuir', 'Mart', 'Puah', 97852531, 'Kent Ridge', '$11.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sunshine33', 'hEntclEc6', 'Sunshine', 'Zhuo', 89989017, 'Eusoff', '$46.29');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('philipa47', '75sjog8BfL', 'Philipa', 'Ang', 96228993, 'Temasek', '$31.02');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kain31', 'QXsNEI', 'Kain', 'Lam', 93404000, 'Raffles', '$31.10');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kiri31', 'rUhXnI67wNV', 'Kiri', 'Huang', 83225774, 'Kent Ridge', '$58.79');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('brittani73', 'SfUfGDu6', 'Brittani', 'Tang', 95636693, 'Sheares', '$7.75');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('abran43', 'ZTyAZxS', 'Abran', 'Lau', 93715900, 'King Edward VII', '$44.83');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('xaviera92', 'BcIMsg8wKi', 'Xaviera', 'Khatri', 89966696, 'Sheares', '$15.15');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('larry5', 'zOGltwrA8Fhc', 'Larry', 'Ang', 83040499, 'Temasek', '$53.25');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('barbe84', 'c4Llm6N', 'Barbe', 'Lam', 89542515, 'Sheares', '$60.21');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('madalyn26', 'I7s9o7bA0d', 'Madalyn', 'Mun', 94944917, 'Eusoff', '$29.89');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('shelly78', 'GcPVkRwG', 'Shelly', 'Peng', 95545137, 'Temasek', '$30.75');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ned96', 'zquGTGkO8', 'Ned', 'Lau', 84688944, 'Kent Ridge', '$27.70');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('benetta75', 'TIECRg80VQy', 'Benetta', 'Jiang', 87329026, 'Eusoff', '$44.38');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('roarke50', 'sRzg3e7943', 'Roarke', 'Kang', 81320109, 'Eusoff', '$10.04');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('robbie23', 'bCwKieF', 'Robbie', 'Nagaratnam', 92807120, 'King Edward VII', '$14.26');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cam42', 'jdZYYBF', 'Cam', 'Wen', 98775113, 'Raffles', '$62.82');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('buiron64', 'KBcbCBJiYF', 'Buiron', 'Toh', 88979038, 'Temasek', '$58.04');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dru75', 'DjJFhOOyK', 'Dru', 'Kuok', 82038773, 'Eusoff', '$50.17');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('alan30', '3CGtpU', 'Alan', 'Ang', 98548733, 'King Edward VII', '$49.78');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('luke30', '8GNSwczg', 'Luke', 'Zhang', 89103805, 'Sheares', '$40.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('uriah54', 'AyYv69EwVxbb', 'Uriah', 'Anandarajah', 86369633, 'Sheares', '$60.24');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('quintilla42', 'bkbpnUMAY3JG', 'Quintilla', 'Qiu', 88717652, 'Kent Ridge', '$47.54');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('therese73', 'k4sYuCE', 'Therese', 'Yang', 81249867, 'Sheares', '$44.21');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nelli17', 'Hj6cER9pIEkI', 'Nelli', 'Mun', 87196525, 'Sheares', '$44.20');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hamlin62', 'aJqHZj', 'Hamlin', 'Patel', 92215508, 'Eusoff', '$5.55');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('billy50', 'yIvEg0txRdz', 'Billy', 'Low', 85486125, 'Temasek', '$44.37');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dasie32', 'XnlpcN', 'Dasie', 'Ma', 96455767, 'Kent Ridge', '$28.32');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('obed27', 'zx6EL6zYb', 'Obed', 'Ko', 90215249, 'Temasek', '$28.79');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('akim86', 'VrOSu68', 'Akim', 'Yuen', 86214322, 'Sheares', '$12.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kit8', '2wFsND0eT', 'Kit', 'Lim', 92566319, 'Kent Ridge', '$32.88');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lanna72', 'V8ErjvgjwBw', 'Lanna', 'Ang', 82472630, 'Eusoff', '$50.78');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('joline37', 'jlFoxpazpEs2', 'Joline', 'Jiang', 91315931, 'Raffles', '$53.02');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('danielle97', 'SUZgZB', 'Danielle', 'Chen', 93542766, 'Kent Ridge', '$36.29');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('marcelo61', 'JWjLGp5f5c', 'Marcelo', 'Huang', 84888032, 'Temasek', '$18.52');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('noah99', 'y9jQug', 'Noah', 'Kuok', 83610977, 'Kent Ridge', '$31.65');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('franni97', 'a63p9izUGma', 'Franni', 'Ow', 92231790, 'Kent Ridge', '$59.78');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('harriott56', 'eATnoCnV2EQ', 'Harriott', '', 88815771, 'Sheares', '$11.35');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('katrina48', '3mWGJyBpT', 'Katrina', 'Jiang', 87854670, 'Eusoff', '$53.06');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tiebold58', 'ZTEK1Xi6MZO', 'Tiebold', 'Leng', 81834506, 'Eusoff', '$27.25');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lacy48', 'SS6s26Ol', 'Lacy', 'Yang', 85216700, 'Temasek', '$49.51');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('pierette64', 'd3dHv6', 'Pierette', 'Sim', 81290486, 'Eusoff', '$45.43');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jessalin30', 'p16nLkgmpLHg', 'Jessalin', 'Kang', 97764390, 'Kent Ridge', '$53.53');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('charline100', '3SyUypWwxTx', 'Charline', 'Ma', 91474652, 'Sheares', '$16.19');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dalia68', 'K71I27bNrZC', 'Dalia', '', 91236323, 'Sheares', '$55.77');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('russ54', 'sRGtK8SH', 'Russ', 'Puah', 82900514, 'King Edward VII', '$37.90');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('annadiana14', 'OT14k9PU', 'Annadiana', 'Puah', 86389613, 'Kent Ridge', '$51.12');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('mariam46', '08xiN1prD', 'Mariam', 'Chen', 91420475, 'Kent Ridge', '$12.46');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('devlen66', 'PVyh1CaLbu', 'Devlen', 'Teh', 93799280, 'Raffles', '$54.10');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dun17', '02AdHqEIVoR', 'Dun', 'Patel', 96071161, 'Sheares', '$16.22');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('aylmer1', 'uZo5eQuc4W', 'Aylmer', 'Lim', 97742874, 'Temasek', '$53.30');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('carlos75', 'sg1XYSJ', 'Carlos', 'Kang', 90128625, 'Raffles', '$30.45');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('mala80', 'yMLnECV', 'Mala', 'Xu', 84409229, 'Eusoff', '$8.10');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hammad24', 'xgLfMizvbUM', 'Hammad', 'Patel', 98096757, 'King Edward VII', '$48.50');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ragnar19', 'QGwnN2RA', 'Ragnar', 'Seet', 90560219, 'Temasek', '$56.08');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hugibert20', 'bkGKPlwDrFX', 'Hugibert', 'Peng', 81864620, 'Kent Ridge', '$64.18');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('eustacia5', '77W6RSbSafH0', 'Eustacia', 'Leng', 98164814, 'Sheares', '$50.13');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('korry25', 'f3nbbOiw9MC', 'Korry', 'Cheang', 98608046, 'King Edward VII', '$32.19');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('isac48', 'I7GVHuSN', 'Isac', 'Kong', 91549460, 'Eusoff', '$7.83');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lelia75', 'xov0Sv', 'Lelia', 'Rao', 85828104, 'Eusoff', '$51.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('astrix43', 'RhP7Bp', 'Astrix', 'Sim', 94423905, 'Kent Ridge', '$35.85');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('clementia94', '9GlFWXivM', 'Clementia', 'Cho', 82934086, 'Raffles', '$22.51');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gasper82', 'eYaHI0c', 'Gasper', 'Pang', 91952387, 'Sheares', '$52.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('deloris96', 'gfhBxEH', 'Deloris', '', 91679377, 'Eusoff', '$34.81');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('marris86', 'qd7pPLK5lFvA', 'Marris', 'Kang', 94867008, 'Raffles', '$51.41');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hayward77', 'tpmtsxJr', 'Hayward', 'Lam', 93279378, 'Temasek', '$47.35');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gusta100', 'u9TRPCyC9gH', 'Gusta', 'Yang', 94459763, 'Eusoff', '$39.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lockwood11', 'N9gLDagvFN', 'Lockwood', 'Teh', 83682226, 'Temasek', '$52.73');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('matt66', 'JdiUUVxue', 'Matt', 'Khatri', 93049799, 'Eusoff', '$8.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('abbott14', '47hKpaLKEVtN', 'Abbott', 'Yuen', 97495816, 'Eusoff', '$49.40');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jean29', 'az0jt9Jh', 'Jean', 'Wen', 89775185, 'Raffles', '$36.53');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('edward46', 'P8oeYV', 'Edward', 'Zhang', 93676224, 'Temasek', '$55.69');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('charisse35', 'E3H6H08aN', 'Charisse', 'Chng', 91880995, 'Raffles', '$17.75');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('welsh76', 'SRXVL3be9t', 'Welsh', 'Anandarajah', 91325029, 'Kent Ridge', '$8.26');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('danielle20', 'eGarEZ', 'Danielle', 'Wong', 92768312, 'Kent Ridge', '$29.00');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tallou17', 'eHWS6Wla0bY', 'Tallou', 'Goh', 98881646, 'Kent Ridge', '$51.90');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('florenza82', 'bxDOtZ', 'Florenza', 'Lim', 88946061, 'King Edward VII', '$39.21');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sylvan37', 'o2azU1', 'Sylvan', 'Kwa', 91660786, 'Kent Ridge', '$38.38');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('hilliard61', 'WCatiJu772n', 'Hilliard', 'Chng', 83349843, 'King Edward VII', '$32.02');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('elliot84', 'wBEgqNfM', 'Elliot', 'Mun', 96211857, 'Sheares', '$33.45');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('darcy91', 'vvvdDn', 'Darcy', 'Leng', 87989168, 'Sheares', '$39.61');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('birdie12', 'bIziawpEPAlz', 'Birdie', 'Chong', 89534777, 'Eusoff', '$62.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('prudence29', 'satNmx5xN', 'Prudence', 'Tang', 97115916, 'Kent Ridge', '$19.29');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('doyle59', 'jXlqN9', 'Doyle', 'Nagaratnam', 84247372, 'Eusoff', '$27.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dorrie8', 'o1DlUdcY', 'Dorrie', 'Chen', 85602268, 'Temasek', '$21.34');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bobinette82', 'BsQO8D', 'Bobinette', 'Xue', 98670770, 'Temasek', '$51.33');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lay28', 'xhCjNn', 'Lay', 'Peng', 93693386, 'Sheares', '$6.73');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cindi72', '9iXtN5U91', 'Cindi', 'Mun', 92323595, 'Temasek', '$52.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dell99', 'FC4oATY', 'Dell', 'Kwa', 93090615, 'Sheares', '$17.28');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('catlee8', 'N22Zrq8aE1', 'Catlee', 'Kang', 81149339, 'Kent Ridge', '$44.43');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dalila67', '2UTQhP', 'Dalila', 'Yang', 93036869, 'Sheares', '$63.68');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('patrick43', '57DluqGQyxtR', 'Patrick', 'Leng', 96794703, 'Eusoff', '$53.68');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jorgan75', '99Xwo8tD10', 'Jorgan', 'Ko', 93434051, 'Eusoff', '$6.66');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('betteann81', 'D4FgslWWj', 'Betteann', 'Xu', 87563221, 'Temasek', '$58.24');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bogart97', 'f8yxmggefyTh', 'Bogart', 'Xue', 88110049, 'Temasek', '$55.56');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('vito59', 'iYwY4sF', 'Vito', 'Leng', 95581201, 'Sheares', '$64.63');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('clarence83', 'hteO0E', 'Clarence', 'Cho', 81739260, 'Temasek', '$5.18');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('norah64', '4Bo53UN', 'Norah', 'Toh', 91289257, 'King Edward VII', '$7.00');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('chelsae87', 'uT0tTtlY', 'Chelsae', 'Patel', 96498875, 'Kent Ridge', '$22.97');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('joel45', 'CX1Ch6X3Q', 'Joel', 'Lam', 82681774, 'Eusoff', '$29.60');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('deva96', 'jsW00t', 'Deva', 'Xu', 92944094, 'Sheares', '$18.17');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('eleanore13', 'FaIBQKI0o', 'Eleanore', 'Chong', 88131931, 'Eusoff', '$40.26');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ethelred51', 'B6ks2zM', 'Ethelred', 'Chan', 89600767, 'Temasek', '$31.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ervin82', 'dnY7AKI3', 'Ervin', 'Yang', 95698214, 'Kent Ridge', '$29.61');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('alexio20', 'ybvW03Ayq', 'Alexio', 'Cho', 92286894, 'Eusoff', '$22.69');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('llewellyn37', 'BomSCkCcc', 'Llewellyn', 'Fan', 94608058, 'Eusoff', '$8.81');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('min52', 'uNpErSYn', 'Min', 'Cho', 91469032, 'Eusoff', '$25.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('erl34', 'q8nZhFJF2aXV', 'Erl', 'Seah', 92988351, 'Eusoff', '$53.25');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('fianna19', 'KcBGUS', 'Fianna', 'Xue', 85422265, 'King Edward VII', '$44.95');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('micah42', 'y5jWThM5wA7V', 'Micah', 'Fan', 98928210, 'Kent Ridge', '$24.85');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('thain4', 'Bp8aX4e3RX', 'Thain', 'Lam', 90743473, 'King Edward VII', '$14.84');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kathrine57', 's1xENt5', 'Kathrine', 'Leng', 98869204, 'Eusoff', '$39.38');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('della94', '2PQxJxXyTX', 'Della', 'Ow', 84572116, 'Temasek', '$57.19');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sharona30', 'HlmA4ToV', 'Sharona', 'Goh', 86794905, 'Sheares', '$60.58');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nicholle26', 'dIamanls7', 'Nicholle', 'Xu', 81406556, 'Kent Ridge', '$37.81');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ransell77', '5WuKpM', 'Ransell', 'Xu', 95284953, 'Sheares', '$57.14');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('shayla67', 'jyIDJE', 'Shayla', 'Patel', 85192832, 'Eusoff', '$31.03');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('estella76', '7oICbASZd', 'Estella', 'Zhuo', 87499522, 'King Edward VII', '$38.27');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jordan32', 'z0ZNkpo9', 'Jordan', 'Zhuo', 93032287, 'Eusoff', '$63.61');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gwenette91', 'dyayAv75S80', 'Gwenette', 'Low', 98647445, 'Kent Ridge', '$27.90');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('harlene75', '5AyszQ', 'Harlene', 'Patel', 88861783, 'Kent Ridge', '$36.58');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('konrad22', '3cNNX54', 'Konrad', 'Ko', 90273242, 'Eusoff', '$56.15');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cynthie20', 'n2m8jqUf', 'Cynthie', 'Leng', 81355714, 'Kent Ridge', '$35.69');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('cammie41', '4CF0HA', 'Cammie', 'Seah', 98708671, 'Temasek', '$45.68');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ernesta56', 'h65vq8VL5k', 'Ernesta', 'Seet', 89994903, 'Eusoff', '$6.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('philippe76', 'MMiSYGojWa', 'Philippe', 'Xu', 95668358, 'Temasek', '$56.79');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('merrel65', 'R5PHjkllZNLb', 'Merrel', 'Huang', 85328010, 'King Edward VII', '$35.03');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('barr65', 'RtOYGl9J', 'Barr', 'Tan', 86377948, 'Sheares', '$40.85');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bendite69', 'aJnQ1qC9ZuI', 'Bendite', 'Ow', 87013588, 'Temasek', '$47.77');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('bobby96', 'IiGrPwA', 'Bobby', 'Ko', 91416685, 'Temasek', '$41.42');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('phillipe79', 'CsAKMNVH1Ld', 'Phillipe', 'Ko', 88915267, 'Sheares', '$23.09');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('rollo15', 'yqy5Q6uYu', 'Rollo', 'Kuok', 97619751, 'King Edward VII', '$7.75');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('alyce49', 'B67b0FzbG', 'Alyce', 'Mun', 82524179, 'Sheares', '$46.79');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lenee21', 'uVwrflLM', 'Lenee', 'Yuen', 85580080, 'King Edward VII', '$55.67');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ashly16', 'Fdaya00OKYd', 'Ashly', 'Zhang', 86077728, 'Kent Ridge', '$62.34');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('baryram32', 'iJs6uP2u', 'Baryram', 'Kuok', 87479393, 'Kent Ridge', '$9.90');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('mallissa53', 'Xx2baGwuCM6', 'Mallissa', 'Cheang', 92973835, 'Eusoff', '$25.36');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nada11', 'E4bwbQeMombV', 'Nada', 'Zhang', 94689101, 'Temasek', '$30.86');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('clay63', 'aEPtaROq', 'Clay', 'Seet', 90695223, 'King Edward VII', '$52.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('carissa60', 'h38wATTx', 'Carissa', 'Ang', 90182320, 'Eusoff', '$39.78');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('clayton38', 'FFCgIGK', 'Clayton', 'Cheang', 81648022, 'Eusoff', '$55.84');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('martyn76', '45s24Y0GnD', 'Martyn', 'Xu', 96105472, 'Raffles', '$54.76');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('jillene4', 'hQUsY2Qcrj', 'Jillene', 'Teh', 87616449, 'Temasek', '$5.12');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dasya77', 'ext1YkY40QEz', 'Dasya', 'Teh', 82209530, 'Sheares', '$25.11');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('vaclav67', 'RaSChCwZksfu', 'Vaclav', 'Low', 87736230, 'Raffles', '$42.63');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('yoko7', 'SOGi1hik', 'Yoko', 'Nagaratnam', 97726113, 'King Edward VII', '$48.04');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('gordon17', 'YZHqmof', 'Gordon', 'Zhuo', 87417259, 'Eusoff', '$56.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('avis43', 'nGqTZ3', 'Avis', 'Tang', 87694209, 'King Edward VII', '$24.53');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('leigh56', 'qrdlsn', 'Leigh', 'Wen', 92807888, 'Kent Ridge', '$35.17');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sayre23', 'eMkI3OKCgi', 'Sayre', 'Cho', 92447660, 'Temasek', '$42.05');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('melosa54', 'mHcykm9', 'Melosa', 'Kwa', 83247168, 'King Edward VII', '$13.51');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('basilius69', 'foMboYSNMIxR', 'Basilius', 'Lee', 81463050, 'Sheares', '$13.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kelsi36', 'Cg1J3aIMg', 'Kelsi', 'Wen', 85054584, 'Raffles', '$24.09');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dorise31', 'z3dD7loqrarx', 'Dorise', 'Chong', 89613945, 'Kent Ridge', '$36.91');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('anthea76', '1iDV8cgpSs', 'Anthea', 'Tang', 84771058, 'Temasek', '$50.02');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('faustina83', 'sB4GOevfdsX', 'Faustina', 'Cho', 87598296, 'Kent Ridge', '$42.89');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('zuzana89', 'ceesDH2Ft', 'Zuzana', 'Seet', 81050811, 'Raffles', '$48.99');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('prentice52', 'HJoXnmtkwtF', 'Prentice', 'Yuen', 92183843, 'King Edward VII', '$48.47');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('mickie40', 'bCxNIdI', 'Mickie', 'Toh', 94561266, 'Raffles', '$25.35');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('neils71', 'RU9pAtqK', 'Neils', 'Puah', 91053760, 'Temasek', '$30.05');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('prescott2', '4sOmY6ab', 'Prescott', 'Peng', 83154472, 'Temasek', '$35.35');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('judah94', 'g1YgchEtb', 'Judah', 'Tang', 97198238, 'King Edward VII', '$12.21');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lyman49', 'YplelT9xt', 'Lyman', 'Wong', 98092810, 'Kent Ridge', '$26.55');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('verena62', 'vwOpWiDaN', 'Verena', 'Ow', 92106000, 'Eusoff', '$33.35');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ashleigh94', 'z3NTgDXCh', 'Ashleigh', 'Qiu', 92252588, 'Raffles', '$21.59');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('barbaraanne85', 'ODlwFHs', 'Barbaraanne', 'Seah', 98163678, 'Sheares', '$55.50');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('giffie25', 'TxbGFR', 'Giffie', 'Chng', 87598818, 'Eusoff', '$10.43');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dorette75', 'CtWgh9053', 'Dorette', 'Lam', 96266570, 'King Edward VII', '$43.21');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lonny97', 'CirKhuXwK', 'Lonny', 'Tang', 84209071, 'Kent Ridge', '$45.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('morna14', 'RsY7JTlcjNm', 'Morna', 'Ko', 83709797, 'Kent Ridge', '$39.14');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('goran53', 'KtSQyG', 'Goran', 'Kuok', 90438525, 'Eusoff', '$55.01');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('anissa18', 'WTO2Wf3', 'Anissa', 'Ma', 97191688, 'Temasek', '$21.15');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('wrennie30', '7RacXv', 'Wrennie', 'Ko', 86344742, 'Sheares', '$40.63');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lev35', 'wSixWK', 'Lev', 'Ang', 93472809, 'Temasek', '$16.32');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('catharina7', 'Meeq2hr', 'Catharina', 'Kuok', 90389955, 'Raffles', '$27.48');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('tony35', 'lsMPnWw', 'Tony', 'Lau', 81751148, 'Eusoff', '$64.17');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('roland88', 'F6PRFF9GGs', 'Roland', 'Khan', 88526122, 'Eusoff', '$44.14');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('wilow34', 'BCX1pURNNIpr', 'Wilow', 'Zhang', 93305110, 'Eusoff', '$60.49');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('blakelee11', 'eVbsewznPNc', 'Blakelee', 'Lau', 82572455, 'Kent Ridge', '$35.02');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('kirby86', 'ZzS7qzSvSqC', 'Kirby', 'Wen', 98464169, 'Eusoff', '$19.16');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('welbie21', 'KhkYcTw', 'Welbie', 'Rao', 81616725, 'Raffles', '$52.80');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('erika77', 'fFwXoXn', 'Erika', 'Kang', 81501241, 'Eusoff', '$44.12');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('lorne18', 'SRxZGlKN', 'Lorne', 'Chng', 89914726, 'Kent Ridge', '$5.24');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('marice74', 'KpcMXHCSw', 'Marice', 'Nagaratnam', 84072590, 'King Edward VII', '$48.36');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('dagny66', 'JmR9mZpdLDg', 'Dagny', 'Wong', 90837991, 'Kent Ridge', '$30.99');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ulric28', 'pXUznU', 'Ulric', 'Xu', 96737397, 'Eusoff', '$47.56');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ailee20', 'Wdj4BD', 'Ailee', 'Kuok', 87075390, 'Raffles', '$15.33');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('nissie94', 'TKB5s8xe', 'Nissie', 'Goh', 97187188, 'King Edward VII', '$12.65');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('costa17', 'RKBMFbf4uI4n', 'Costa', 'Chan', 91685624, 'King Edward VII', '$60.77');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('juliana55', 'CCT9ddc', 'Juliana', 'Patel', 87957159, 'Temasek', '$56.55');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('katusha54', 'DprPTwHj', 'Katusha', 'Goh', 84772887, 'Kent Ridge', '$36.17');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('fabio49', 'XJeziUv', 'Fabio', 'Kang', 94099456, 'Sheares', '$50.33');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ezequiel17', 'aR9Zo7', 'Ezequiel', 'Kwa', 84119447, 'Temasek', '$63.46');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('glynda88', 'yDB7M6Z', 'Glynda', 'Rao', 96333129, 'King Edward VII', '$47.14');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('shepperd48', 'Q0rrRnH', 'Shepperd', 'Shih', 87779029, 'Sheares', '$60.03');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('georgeanne76', 'wr1rZECMcDfg', 'Georgeanne', 'Chng', 85595866, 'Temasek', '$49.24');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('antons44', 'KoKcCN', 'Antons', 'Lee', 93203016, 'Raffles', '$9.57');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('mae92', '6GjmDKiR', 'Mae', 'Xu', 88123317, 'King Edward VII', '$30.54');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('ephraim87', '2Af09V', 'Ephraim', 'Ow', 91307965, 'Kent Ridge', '$62.36');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('sanders37', 'QYui3jCS', 'Sanders', 'Lau', 98471563, 'Kent Ridge', '$9.92');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('falito41', 'r8G9mz', 'Falito', 'Chan', 87844325, 'Kent Ridge', '$9.57');
insert into buyer (username, password, first_name, last_name, phone_number, hall, wallet_balance) values ('orville25', 'AUBuo3bA', 'Orville', 'Nagaratnam', 95733339, 'Eusoff', '$52.32');
