insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Plain Papadum', '$0.8');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Butter Chicken', '$12.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Garlic Naan', '$2.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Mushroom Rice', '$3.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Paneer Tikka Masala', '$8.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Mango Chutney', '$0.5');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Plain Naan', '$2.6');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Tandoori Chicken (1/4)', '$4.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Lamb Maggi Goreng', '$7.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Chapati', '$1.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Lamb Tikka', '$4.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Saag Paneer', '$5.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Cheese Naan', '$4.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Chicken Maggi Goreng', '$5.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Chicken Chilli Garlic', '$9.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Lamb Biryani', '$9.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Keema Naan', '$2.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Red Sauce', '$0.5');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Korma - Prawn', '$9.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Garlic Cheese Naan', '$5.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Chicken Balti', '$9.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Special Fried Rice', '$3.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Chicken Tikka Masala', '$8.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Curry - Lamb', '$7.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Vegetable Rice', '$3.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Saag - Prawn', '$9.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Tandoori Chicken Masala', '$8.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Lamb Tikka Chilli Masala', '$8.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Milo Shake', '$5.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Milo Dinosaur', '$5.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Coke Float', '$5.95');
insert into item (shopname, item, price) values ('Al Amaan Restaurant', 'Lemon Tea', '$2.5');
insert into item (shopname, item, price) values ('Formosa Delights', 'Lobster Taco', '$12');
insert into item (shopname, item, price) values ('Formosa Delights', 'Breakfast Tacos', '$10');
insert into item (shopname, item, price) values ('Formosa Delights', 'Breakfast Burrito', '$16');
insert into item (shopname, item, price) values ('Formosa Delights', 'Shrimp Tacos', '$12');
insert into item (shopname, item, price) values ('Formosa Delights', 'Tuna Tacos', '$11');
insert into item (shopname, item, price) values ('Formosa Delights', 'Fish Tacos', '$9.5');
insert into item (shopname, item, price) values ('Formosa Delights', 'Pork Burrito', '$8.09');
insert into item (shopname, item, price) values ('Formosa Delights', 'Pork Burrito Bowl', '$7.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Barbacoa Burrito', '$7.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Ground Sirloin Burrito', '$7.89');
insert into item (shopname, item, price) values ('Formosa Delights', 'Fajita Steak Taco', '$7.79');
insert into item (shopname, item, price) values ('Formosa Delights', 'Chicken Burrito', '$7.79');
insert into item (shopname, item, price) values ('Formosa Delights', 'Mixed Vegetable Burrito', '$7.59');
insert into item (shopname, item, price) values ('Formosa Delights', 'Chicken Burrito Bowl', '$7.59');
insert into item (shopname, item, price) values ('Formosa Delights', 'Pork Taco', '$7.39');
insert into item (shopname, item, price) values ('Formosa Delights', 'Barbacoa Taco', '$7.29');
insert into item (shopname, item, price) values ('Formosa Delights', 'Ground Sirloin Taco', '$7.19');
insert into item (shopname, item, price) values ('Formosa Delights', 'Mixed Vegetable Taco', '$7.09');
insert into item (shopname, item, price) values ('Formosa Delights', 'Soft Taco', '$4');
insert into item (shopname, item, price) values ('Formosa Delights', 'Kids Taco', '$4');
insert into item (shopname, item, price) values ('Formosa Delights', 'Fiesta Tacos', '$9.79');
insert into item (shopname, item, price) values ('Formosa Delights', 'Barbacoa', '$7.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Tender Beef Tacos', '$6.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Taco Dinner', '$6.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Soft Chicken Fajita Tacos', '$6.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Small Ground Beef Burrito', '$6.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Shredded Chicken Taco', '$6.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Ground Beef Taco', '$6.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Burrito Plate', '$9.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Beef or Chicken Taco Bowl', '$6.29');
insert into item (shopname, item, price) values ('Formosa Delights', 'Soft Chicken Tacos', '$5.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Crispy Ground Beef Taco', '$5.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Burrito', '$2.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Beef Puffed Taco', '$9.99');
insert into item (shopname, item, price) values ('Formosa Delights', 'Beef Burrito', '$15');
insert into item (shopname, item, price) values ('Super Snacks', 'Asada Taco', '$1.75');
insert into item (shopname, item, price) values ('Super Snacks', 'Chile Verde Burrito', '$14.95');
insert into item (shopname, item, price) values ('Super Snacks', 'Been and Cheese Burrito', '$9.95');
insert into item (shopname, item, price) values ('Super Snacks', 'The Ultimate Breakfast Burrito', '$10.5');
insert into item (shopname, item, price) values ('Super Snacks', 'Breakfast Tacos', '$5.25');
insert into item (shopname, item, price) values ('Super Snacks', 'Supper Taco', '$6.75');
insert into item (shopname, item, price) values ('Super Snacks', 'Burrito Bowl', '$6.75');
insert into item (shopname, item, price) values ('Super Snacks', '2 Soft Tacos', '$5');
insert into item (shopname, item, price) values ('Super Snacks', 'Burrito Poblano', '$7.75');
insert into item (shopname, item, price) values ('Super Snacks', '2 Tacos', '$6.4');
insert into item (shopname, item, price) values ('Super Snacks', 'Burrito Suize', '$5.25');
insert into item (shopname, item, price) values ('Super Snacks', 'Mexican Taco', '$17.99');
insert into item (shopname, item, price) values ('Super Snacks', 'Ahi Tuna Tartare Tacos', '$12');
insert into item (shopname, item, price) values ('Super Snacks', 'Tex Mex Burritos', '$14.25');
insert into item (shopname, item, price) values ('Super Snacks', 'Sante Fe Burrito', '$11.99');
insert into item (shopname, item, price) values ('Super Snacks', 'Burritos', '$11.79');
insert into item (shopname, item, price) values ('Super Snacks', 'Tacos', '$11.75');
insert into item (shopname, item, price) values ('Super Snacks', 'Soft Tacos', '$11.75');
insert into item (shopname, item, price) values ('Super Snacks', 'Finger Tacos', '$7.99');
insert into item (shopname, item, price) values ('Super Snacks', 'Ice Cream Taco', '$3.25');
insert into item (shopname, item, price) values ('Fong Seng', 'Nasi Lemak Set A', '$3.50');
insert into item (shopname, item, price) values ('Fong Seng', 'Nasi Lemak Set B', '$4.50');
insert into item (shopname, item, price) values ('Fong Seng', 'Nasi Lemak Set C', '$3.50');
insert into item (shopname, item, price) values ('Fong Seng', 'Nasi Lemak Set D', '$4.00');
insert into item (shopname, item, price) values ('Fong Seng', 'Nasi Lemak Set E', '$5.00');
insert into item (shopname, item, price) values ('Fong Seng', 'Lemon Tea', '$2.00');
insert into item (shopname, item, price) values ('Fong Seng', 'Milo', '$3.00');
insert into item (shopname, item, price) values ('Fong Seng', 'Lime Juice', '$1.50');
